### ISSUE TITLE
建议长按相应方向键的时候能够能够自动滚动。

### ISSUE THREAD

**Issue by ihuguowei** [code-artisan/react-select#3]
RT
求加定时器，改进用户体验。

**Comment by code-artisan** [comment]
定时器？干嘛用？

**Comment by ihuguowei** [comment]
@code-artisan 我以前写滚动条的时候实现长按按钮自动滚动就是，监听`mousedown`就开一个定时器自动填充偏移，`mouseup`的时候清除定时器，不知道你是咋实现长按滚动的。所以就提了定时器这个东西。

**Comment by code-artisan** [comment]
@ihuguowei 只需要把 `keyup` 换成 `keydown` 就好了，下个版本就改过来了哈 :smile:
